### ISSUE TITLE
AsyncWebSocketClient 有bug

### ISSUE THREAD

**Issue by sttacckz** [gaochundong/Cowboy.WebSockets#1]
具体是server还是client不熟悉源码就不下结论了.
开启Cowboy.WebSockets.TestAsyncWebSocketServer
然后开AsyncWebSocketClient,发送many,发送 big100,然后等有ping,pong响应,再次发送数据server没有显示有数据过来.

然后我看了你博客说SegmentBufferManager回收不是缓存分配的或许用GetHashCode()可以解决?

不知道能否给Send增加个回调,这样我发送完成可以重复使用发送缓存.

**Comment by gaochundong** [comment]
重复问题，通过 Issue #2 进行跟踪。
